[workspace]

members = [
    "creational/builder",
    "creational/factory",
    "creational/abstract_factory",
    "creational/singleton",



    "behaviour/state",
    
    
    
    "structural/decorator",
    "structural/adapter",
    "structural/facade"
]